services:
  apache:
    build: .
    restart: always
    ports:
      - 8080:80

  mysql:
    image: mariadb:5.5.64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql

  otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:latest
    environment:
      - SPLUNK_ACCESS_TOKEN
      - SPLUNK_REALM=us0
      - SPLUNK_HEC_TOKEN
      - SPLUNK_HEC_URL
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver

volumes:
  db:
