receivers:
  nmap:
    interval: 10s
    scanner_arguments: "-sV --script=default,vulners -p- localhost"

processors:
  batch:

exporters:
  splunk_hec:
    token: "${SPLUNK_HEC_TOKEN}"
    endpoint: "${SPLUNK_HEC_URL}"
    source: "otel"
    sourcetype: "otel"
    profiling_data_enabled: false
  otlp: # sending
    endpoint: "localhost:4317"
    compression: none
    tls:
      insecure: true
  debug:
    verbosity: basic # detailed

service:
  pipelines:
    logs:
      receivers: 
      - nmap
      processors:
      - batch
      exporters:
      - debug
      - otlp
      - splunk_hec
  telemetry:
    logs:
      level: debug
